### ISSUE TITLE
Ldr(Req) have a bug.

### ISSUE THREAD

**Issue by kwanggaeto** [axldns/AXL-library#1]
you said that Ldr is able to Load all files in directory. but, it can't recognize directory.

the reason is a 'if' condition in addPathes() of Req is wrong.

currently, the if condition was written "if(getQuaifiedClassName(v) == 'File')". 
but, it have to change to if(getQuaifiedClassName(v) == "flash.filesystems:File")"

i'm using Animate CC 2015.2 and AIR 21.0 of Desktop.

thanks.

**Comment by axldns** [comment]
@kwanggaeto thanks for your diligence!  I was able to reproduce the bug. Fix applied, tests passed, changes pushed as [1.2.2]. Thanks for contributing!
